# -*- coding: utf-8 -*-
"""1210_steering_OLMo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OQthi9Xzk7Gl_1lxX6IbnB6HRwZ62jbL
"""

!pip install -q transformers accelerate sentencepiece torch datasets scikit-learn scipy seaborn

from huggingface_hub import login
login()

# ------------------------------------------------------------
# 0. Imports & Model Load
# ------------------------------------------------------------

import os
import re
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import spearmanr
import seaborn as sns
from tqdm.auto import tqdm
from sklearn.metrics.pairwise import cosine_similarity
from transformers import AutoTokenizer, AutoModelForCausalLM

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

model_name = "allenai/Olmo-3-1025-7B"
print("Loading:", model_name)

tokenizer = AutoTokenizer.from_pretrained(
    model_name,
    trust_remote_code=True
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16,
    trust_remote_code=True
)

model.eval()

print("Num layers:", model.config.num_hidden_layers)
print("Hidden dim:", model.config.hidden_size)

# ------------------------------------------------------------
# 1. Utility Functions (Embedding Extraction)
# ------------------------------------------------------------

def extract_hidden_single(text: str, layer: int):
    """
    Returns mean-pooled hidden embedding at a specific layer.
    """
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=200
    ).to(model.device)

    with torch.no_grad():
        outputs = model(**inputs, output_hidden_states=True)
        h = outputs.hidden_states[layer]          # [1, seq, dim]
        mask = inputs["attention_mask"].unsqueeze(-1)

        masked = h * mask
        summed = masked.sum(dim=1)
        length = mask.sum(dim=1).clamp(min=1)
        emb = summed / length                     # [1, dim]

    return emb.squeeze(0)   # ✅ GPU tensor 그대로 반환

# ------------------------------------------------------------
# 2. Cosine Similarity
# ------------------------------------------------------------

def cos_sim(a, b):
    a = a / (a.norm(p=2) + 1e-8)
    b = b / (b.norm(p=2) + 1e-8)
    return float((a * b).sum())

# ------------------------------------------------------------
# 3. Layer Detection (Internal Embedding Difference)
# ------------------------------------------------------------

def extract_last_token_states(df, model, tokenizer):
    cache = {}

    for _, row in df.iterrows():
        for key in ["logical", "pragmatic"]:
            sent = row[key]

            if sent not in cache:
                inputs = tokenizer(
                    sent,
                    return_tensors="pt",
                    truncation=True,
                    max_length=128
                ).to(model.device)

                with torch.no_grad():
                    outputs = model(
                        **inputs,
                        output_hidden_states=True
                    )

                hidden_states = outputs.hidden_states

                layer_embs = []
                for layer in range(len(hidden_states)):
                    emb = hidden_states[layer][0, -1].detach().cpu()
                    layer_embs.append(emb)

                cache[sent] = layer_embs

    return cache


def cosine_score_for_layer_cached(df, cache, layer):
    scores = []

    for _, row in df.iterrows():
        l = cache[row["logical"]][layer].numpy().reshape(1, -1)
        p = cache[row["pragmatic"]][layer].numpy().reshape(1, -1)

        sim_lp = cosine_similarity(l, p)[0][0]
        scores.append(1 - sim_lp)  # separation score

    return np.mean(scores)


def detect_layer(df, model, tokenizer):
    print("\nDetecting layers ...")

    cache = extract_last_token_states(df, model, tokenizer)

    for L in range(model.config.num_hidden_layers):
        s = cosine_score_for_layer_cached(df, cache, L)
        print(f"Layer {L}: score={s:.4f}")

# ------------------------------------------------------------
# 4. Steering Vector
# ------------------------------------------------------------

def compute_steering_vector(df, layer):
    logical_vecs = []
    pragmatic_vecs = []

    for _, row in df.iterrows():
        logical_vecs.append(extract_hidden_single(row["logical"], layer))
        pragmatic_vecs.append(extract_hidden_single(row["pragmatic"], layer))

    logical_mean = torch.stack(logical_vecs).mean(dim=0)
    pragmatic_mean = torch.stack(pragmatic_vecs).mean(dim=0)

    v = pragmatic_mean - logical_mean
    v = v / v.norm()     # normalize
    return v

# ------------------------------------------------------------
# 5. Compute steering direction from multiple layers
# ------------------------------------------------------------


def compute_direction_multi_layers(df, layers):
    vecs = []

    print(f"\nComputing steering direction from {len(df)} samples...")

    for _, row in tqdm(df.iterrows(), total=len(df), desc="Computing direction"):
        p = row["pragmatic"]
        l = row["logical"]

        vec_p = []
        vec_l = []

        for layer in layers:
            vec_p.append(extract_hidden_single(p, layer))
            vec_l.append(extract_hidden_single(l, layer))

        vec_p = torch.cat(vec_p)
        vec_l = torch.cat(vec_l)

        vecs.append(vec_p - vec_l)

    direction = torch.stack(vecs).mean(dim=0)
    direction = direction / direction.norm()

    print("✅ Direction computed.")
    return direction

# ------------------------------------------------------------
# 6. Steering evaluation metric
# ------------------------------------------------------------

def evaluate_with_steering(df, out_path, layers, direction, fixed_alpha=None):
    rows = []
    print(f"\nEvaluating {len(df)} samples...")

    # --- helper: multi-layer embedding ---
    def get_multi_layer_emb(text, layers):
        embs = []
        for L in layers:
            embs.append(extract_hidden_single(text, L))
        return torch.cat(embs)

    for _, row in tqdm(df.iterrows(), total=len(df), desc="Processing"):
        row_dict = row.to_dict()

        anchor    = row["anchor"]
        logical   = row["logical"]
        pragmatic = row["pragmatic"]
        grade     = row["grade"]

        # --- baseline embeddings (multi-layer) ---
        a_emb = get_multi_layer_emb(anchor, layers)
        l_emb = get_multi_layer_emb(logical, layers)
        p_emb = get_multi_layer_emb(pragmatic, layers)

        # baseline similarities
        sim_int_log  = cos_sim(a_emb, l_emb)
        sim_int_prag = cos_sim(a_emb, p_emb)

        pref_int = 1 if sim_int_prag > sim_int_log else 0

        # alpha
        alpha = fixed_alpha if fixed_alpha is not None else alpha_from_grade(grade)

        # steering
        steered = (a_emb + alpha * direction)
        steered = steered / steered.norm()

        sim_st_log  = cos_sim(steered, l_emb)
        sim_st_prag = cos_sim(steered, p_emb)

        pref_st = 1 if sim_st_prag > sim_st_log else 0

        # merge results
        row_dict.update({
            "alpha": alpha,

            "sim_internal_logical": sim_int_log,
            "sim_internal_pragmatic": sim_int_prag,
            "pref_internal": pref_int,

            "sim_steered_logical": sim_st_log,
            "sim_steered_pragmatic": sim_st_prag,
            "pref_steered": pref_st,
        })

        rows.append(row_dict)

    pd.DataFrame(rows).to_csv(out_path, index=False)
    print("Saved:", out_path)

# ------------------------------------------------------------
# 7. α (alpha) setting
# ------------------------------------------------------------

grade_to_numeric = {
    "A": 1.0,
    "B": 0.75,
    "C": 0.5,
    "D": 0.25,
    "E": 0.0
}

ALPHA_MIN = 1.0
ALPHA_MAX = 15.0

def alpha_from_grade(g):
    g_num = grade_to_numeric[g]
    return ALPHA_MIN + (ALPHA_MAX - ALPHA_MIN) * g_num

from google.colab import drive
drive.mount('/content/drive')

# ------------------------------------------------------------
# 8. Main pipeline
# ------------------------------------------------------------

# Load dataset
df = pd.read_csv("augmented_data.csv")

# df_probe = (
#     df.groupby(["weak", "strong"], group_keys=False)
#       .apply(lambda x: x.sample(n=1))
#       .sample(n=121, random_state=0)
# )

# # Detect Layers
# detect_layer(df_probe, model, tokenizer)

# Detecting layers ...
# Layer 0: score=0.0000
# Layer 1: score=0.0018
# Layer 2: score=0.0056
# Layer 3: score=0.0145
# Layer 4: score=0.0336
# Layer 5: score=0.0384
# Layer 6: score=0.0476
# Layer 7: score=0.0742
# Layer 8: score=0.0953
# Layer 9: score=0.1074
# Layer 10: score=0.1206
# Layer 11: score=0.1382
# Layer 12: score=0.1473
# Layer 13: score=0.1614
# Layer 14: score=0.1641
# Layer 15: score=0.1734
# Layer 16: score=0.1802
# Layer 17: score=0.1693
# Layer 18: score=0.1650
# Layer 19: score=0.1579
# Layer 20: score=0.1597
# Layer 21: score=0.1575
# Layer 22: score=0.1560
# Layer 23: score=0.1564
# Layer 24: score=0.1590
# Layer 25: score=0.1582
# Layer 26: score=0.1531
# Layer 27: score=0.1542
# Layer 28: score=0.1524
# Layer 29: score=0.1402
# Layer 30: score=0.1047
# Layer 31: score=0.0750

# Compute Steering Vector
df_dir = (
    df.groupby(["weak", "strong"], group_keys=False)
      .apply(lambda x: x.sample(n=3, random_state=42))
      .reset_index(drop=True)
)

layers = [15, 16, 17, 18]  # separation score 0.165 넘던 레이어들

# direction = compute_direction_multi_layers(df_dir, layers)
# torch.save(
#     direction,
#     "/content/drive/MyDrive/direction.pt"
# )

direction = torch.load(
    "/content/drive/MyDrive/direction.pt",
    map_location=model.device
)

# Evaluate (Fixed alpha)
evaluate_with_steering(
    df,
    "/content/drive/MyDrive/results_steered_fixed_alpha.csv",
    layers,
    direction,
    fixed_alpha=15.0
)

direction = torch.load(
    "/content/drive/MyDrive/direction.pt",
    map_location=model.device
)

# Evaluate (Gradient alpha)
evaluate_with_steering(
    df,
    "/content/drive/MyDrive/results_steered_grad_alpha.csv",
    layers,
    direction
)

# ------------------------------------------------------------
# 9. Visualization (Bar)
# ------------------------------------------------------------

def plot_pragmatic_winrate(csv_path, pref_col, title, bar_color="#1f77b4"):
    df = pd.read_csv(csv_path)
    df["lex_item"] = df["weak"] + "–" + df["strong"]

    win_rate = (
        df.groupby("lex_item")[pref_col]
          .mean()
          .sort_values(ascending=False)
    )

    plt.figure(figsize=(10, 20))
    sns.barplot(
        x=win_rate.values,
        y=win_rate.index,
        color=bar_color
    )
    plt.title(title, fontsize=14)
    plt.xlabel("")
    plt.ylabel("")
    plt.xlim(0, 1)
    plt.tight_layout()
    plt.show()


plot_pragmatic_winrate(
    "/content/drive/MyDrive/results_steered_fixed_alpha.csv",
    pref_col="pref_internal",
    title="Baseline"
)

plot_pragmatic_winrate(
    "/content/drive/MyDrive/results_steered_fixed_alpha.csv",
    pref_col="pref_steered",
    title="Fixed-α Steering"
)

plot_pragmatic_winrate(
    "/content/drive/MyDrive/results_steered_grad_alpha.csv",
    pref_col="pref_steered",
    title="Gradient-α Steering"
)

# ------------------------------------------------------------
# 10. Visualization (Baseline-Fixed Steering)
# ------------------------------------------------------------

df = pd.read_csv("/content/drive/MyDrive/results_steered_fixed_alpha.csv")

plt.style.use("seaborn-v0_8")
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# ============================
# (1) Baseline Internal similarity
# ============================

ax1 = axes[0]

sns.kdeplot(
    x=df["sim_internal_pragmatic"],
    y=df["sim_internal_logical"],
    fill=True, cmap="Blues", thresh=0.05, levels=10, ax=ax1
)
sns.scatterplot(
    x=df["sim_internal_pragmatic"],
    y=df["sim_internal_logical"],
    s=25, alpha=0.5, ax=ax1
)

lim_min = min(df["sim_internal_pragmatic"].min(), df["sim_internal_logical"].min())
lim_max = max(df["sim_internal_pragmatic"].max(), df["sim_internal_logical"].max())

ax1.plot([lim_min, lim_max], [lim_min, lim_max], "r--")
ax1.set_title("Baseline")
ax1.set_xlabel("Pragmatic similarity")
ax1.set_ylabel("Logical similarity")
ax1.set_xlim(lim_min, lim_max)
ax1.set_ylim(lim_min, lim_max)


# ============================
# (2) Steered (Fixed-alpha)
# ============================

ax2 = axes[1]

sns.kdeplot(
    x=df["sim_steered_pragmatic"],
    y=df["sim_steered_logical"],
    fill=True, cmap="Blues", thresh=0.05, levels=10, ax=ax2
)
sns.scatterplot(
    x=df["sim_steered_pragmatic"],
    y=df["sim_steered_logical"],
    s=25, alpha=0.5, ax=ax2
)

lim_min2 = min(df["sim_steered_pragmatic"].min(), df["sim_steered_logical"].min())
lim_max2 = max(df["sim_steered_pragmatic"].max(), df["sim_steered_logical"].max())

ax2.plot([lim_min2, lim_max2], [lim_min2, lim_max2], "r--")
ax2.set_title("Fixed-α Steering")
ax2.set_xlabel("Pragmatic similarity")
ax2.set_ylabel("Logical similarity")
ax2.set_xlim(lim_min2, lim_max2)
ax2.set_ylim(lim_min2, lim_max2)

plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# 11. Visualization (Baseline-Gradient Steering)
# ------------------------------------------------------------

grades = ["A", "B", "C", "D", "E"]

df_base = pd.read_csv("/content/drive/MyDrive/results_steered_grad_alpha.csv")

plt.style.use("seaborn-v0_8")

fig, axes = plt.subplots(2, len(grades), figsize=(20, 8))


# ============================
# (1) Baseline Internal similarity
# ============================

lim_min_base = min(
    df_base["sim_internal_pragmatic"].min(),
    df_base["sim_internal_logical"].min()
)
lim_max_base = max(
    df_base["sim_internal_pragmatic"].max(),
    df_base["sim_internal_logical"].max()
)


# ============================
# (2) Steered (Gradient-alpha)
# ============================

lim_min_st = min(
    df_base["sim_steered_pragmatic"].min(),
    df_base["sim_steered_logical"].min()
)
lim_max_st = max(
    df_base["sim_steered_pragmatic"].max(),
    df_base["sim_steered_logical"].max()
)

for i, g in enumerate(grades):

    sub = df_base[df_base["grade"] == g]

    # -------------------------------------------------
    # (1) Baseline — Row 0, Column i
    # -------------------------------------------------
    ax1 = axes[0, i]

    if len(sub) > 0:
        sns.kdeplot(
            data=sub,
            x="sim_internal_pragmatic",
            y="sim_internal_logical",
            fill=True, cmap="Blues", thresh=0.05, levels=10, ax=ax1
        )
        sns.scatterplot(
            data=sub,
            x="sim_internal_pragmatic",
            y="sim_internal_logical",
            color="black", alpha=0.5, s=25, ax=ax1
        )

    # baseline limits 적용
    ax1.plot([lim_min_base, lim_max_base], [lim_min_base, lim_max_base], "r--", linewidth=1)
    ax1.set_title(f"Grade {g} — Baseline")
    ax1.set_xlim(lim_min_base, lim_max_base)
    ax1.set_ylim(lim_min_base, lim_max_base)
    ax1.set_xlabel("")
    ax1.set_ylabel("")

    # -------------------------------------------------
    # (2) Steering — Row 1, Column i
    # -------------------------------------------------
    ax2 = axes[1, i]

    if len(sub) > 0:
        sns.kdeplot(
            data=sub,
            x="sim_steered_pragmatic",
            y="sim_steered_logical",
            fill=True, cmap="Blues", thresh=0.05, levels=10, ax=ax2
        )
        sns.scatterplot(
            data=sub,
            x="sim_steered_pragmatic",
            y="sim_steered_logical",
            color="black", alpha=0.5, s=25, ax=ax2
        )

    # steering limits
    ax2.plot([lim_min_st, lim_max_st], [lim_min_st, lim_max_st], "r--", linewidth=1)
    ax2.set_title(f"Grade {g} — Gradient-α Steering")
    ax2.set_xlim(lim_min_st, lim_max_st)
    ax2.set_ylim(lim_min_st, lim_max_st)
    ax2.set_xlabel("")
    ax2.set_ylabel("")

# Label
fig.suptitle("", fontsize=18)
fig.text(0.5, 0.01, "Pragmatic similarity", ha="center", fontsize=12)
fig.text(0.04, 0.5, "Logical similarity", va="center", rotation="vertical", fontsize=12)

plt.tight_layout(rect=[0.05, 0.03, 1, 0.93])
plt.show()

# ------------------------------------------------------------
# 12. Spearson
# ------------------------------------------------------------

def compute_spearman(
    baseline_csv,
    steered_csv,
    pref_baseline="pref_internal",
    pref_steered="pref_steered"
):

    df_base = pd.read_csv(baseline_csv)
    df_st   = pd.read_csv(steered_csv)

    # lexical item
    df_base["lex_item"] = df_base["weak"] + "–" + df_base["strong"]
    df_st["lex_item"]   = df_st["weak"] + "–" + df_st["strong"]

    # pragmatic win-rate
    base_wr = (
        df_base.groupby("lex_item")[pref_baseline]
               .mean()
               .rename("baseline")
    )
    st_wr = (
        df_st.groupby("lex_item")[pref_steered]
             .mean()
             .rename("steered")
    )

    # align
    df_merge = pd.concat([base_wr, st_wr], axis=1).dropna()

    rho, p = spearmanr(df_merge["baseline"], df_merge["steered"])

    return rho, p, df_merge


rho_fixed, p_fixed, df_fixed = compute_spearman(
    baseline_csv="/content/drive/MyDrive/results_steered_fixed_alpha.csv",
    steered_csv="/content/drive/MyDrive/results_steered_fixed_alpha.csv",
    pref_baseline="pref_internal",
    pref_steered="pref_steered"
)

print("=== Spearman (Baseline vs Fixed α) ===")
print(f"ρ = {rho_fixed:.3f}, p = {p_fixed:.4g}")


rho_grad, p_grad, df_grad = compute_spearman(
    baseline_csv="/content/drive/MyDrive/results_steered_grad_alpha.csv",
    steered_csv="/content/drive/MyDrive/results_steered_grad_alpha.csv",
    pref_baseline="pref_internal",
    pref_steered="pref_steered"
)

print("=== Spearman (Baseline vs Grad α) ===")
print(f"ρ = {rho_grad:.3f}, p = {p_grad:.4g}")

from scipy.stats import wilcoxon
import pandas as pd

# ------------------------------------------------------------
# 13. Wilcoxon signed-rank test
# ------------------------------------------------------------

def compute_wilcoxon(
    csv_path,
    pref_baseline="pref_internal",
    pref_steered="pref_steered"
):
    df = pd.read_csv(csv_path)

    # lexical item
    df["lex_item"] = df["weak"] + "–" + df["strong"]

    # pragmatic win-rate
    base_wr = (
        df.groupby("lex_item")[pref_baseline]
          .mean()
          .rename("baseline")
    )

    st_wr = (
        df.groupby("lex_item")[pref_steered]
          .mean()
          .rename("steered")
    )

    # align
    df_merge = pd.concat([base_wr, st_wr], axis=1).dropna()

    # difference (steered - baseline)
    diff = df_merge["steered"] - df_merge["baseline"]

    # Wilcoxon signed-rank test
    stat, p = wilcoxon(diff)

    return stat, p, df_merge



stat_fixed, p_fixed_w, df_fixed_w = compute_wilcoxon(
    csv_path="/content/drive/MyDrive/results_steered_fixed_alpha.csv",
    pref_baseline="pref_internal",
    pref_steered="pref_steered"
)

print("=== Wilcoxon (Baseline vs Fixed α) ===")
print(f"stat = {stat_fixed:.3f}, p = {p_fixed_w:.4g}")


stat_grad, p_grad_w, df_grad_w = compute_wilcoxon(
    csv_path="/content/drive/MyDrive/results_steered_grad_alpha.csv",
    pref_baseline="pref_internal",
    pref_steered="pref_steered"
)

print("=== Wilcoxon (Baseline vs Grad α) ===")
print(f"stat = {stat_grad:.3f}, p = {p_grad_w:.4g}")

from scipy.stats import wilcoxon

def grade_wilcoxon(csv_path):
    df = pd.read_csv(csv_path)
    df["lex_item"] = df["weak"] + "–" + df["strong"]

    results = {}

    for g in ["A", "B", "C", "D", "E"]:
        sub = df[df["grade"] == g]

        if len(sub) < 5:
            continue

        base = sub.groupby("lex_item")["pref_internal"].mean()
        steered = sub.groupby("lex_item")["pref_steered"].mean()

        merged = pd.concat([base, steered], axis=1).dropna()
        merged.columns = ["baseline", "steered"]

        stat, p = wilcoxon(merged["baseline"], merged["steered"])
        results[g] = (stat, p)

    return results


print("=== Grade-wise Wilcoxon (Fixed α) ===")
print(grade_wilcoxon("/content/drive/MyDrive/results_steered_fixed_alpha.csv"))

print("\n=== Grade-wise Wilcoxon (Gradient α) ===")
print(grade_wilcoxon("/content/drive/MyDrive/results_steered_grad_alpha.csv"))

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

def plot_delta_hist(csv_path, title):
    df = pd.read_csv(csv_path)
    df["lex_item"] = df["weak"] + "–" + df["strong"]

    base = df.groupby("lex_item")["pref_internal"].mean()
    steered = df.groupby("lex_item")["pref_steered"].mean()

    delta = (steered - base).dropna()

    plt.figure(figsize=(7, 4))
    sns.histplot(delta, bins=20, kde=True, color="#1f77b4")
    plt.axvline(0, color="red", linestyle="--")
    plt.xlabel("")
    plt.ylabel("")
    plt.title(title)
    plt.tight_layout()
    plt.show()

plot_delta_hist(
    "/content/drive/MyDrive/results_steered_fixed_alpha.csv",
    "Δ Pragmatic intepretation rate (Fixed-α steering)"
)

plot_delta_hist(
    "/content/drive/MyDrive/results_steered_grad_alpha.csv",
    "Δ Pragmatic intepretation rate (Gradient-α steering)"
)

"""---

# 🎯 **Steering Experiment Pipeline — Step-by-Step Explanation**

---

# **0. Imports & Model Load**

### 📌 역할

* 전체 실험에서 사용할 라이브러리 로드
* LLaMA 모델과 tokenizer를 불러오고 GPU로 올림
* 이후 모든 embedding 및 generation 작업이 여기서 로드한 모델을 사용함

### 🔍 핵심

* 모델 로딩은 단 한 번만 해야 함
* `output_hidden_states=True`로 설정해야 **layer probing + steering**이 가능해짐

---

# **1. Utility Functions (Embedding Extraction)**

### 📌 역할

문장 텍스트(문자열)를 → **특정 레이어의 embedding 벡터(숫자)** 로 변환하는 핵심 함수.

### 🔍 동작

* 모델에 text 입력
* hidden states 가져오기
* 지정한 layer의 hidden state 선택
* attention mask 기반 mean pooling → sentence-level embedding 생성

### 🎯 왜 필요?

* steering vector 생성도
* baseline similarity 계산도
* steered similarity 계산도

모든 embedding 관련 계산의 출발점.

---

# **2. Cosine Similarity Function**

### 📌 역할

두 벡터의 의미적 유사도를 측정.

### 🔍 이유

* anchor vs logical
* anchor vs pragmatic
* steered_anchor vs logical
* steered_anchor vs pragmatic

이 네 가지 비교를 모두 cosine similarity로 수행.

---

# **3. Layer Detection (Internal Representation Separation Test)**

### 📌 역할

문장쌍(logical vs pragmatic)의 의미 차이가 **가장 잘 분리되는 layer**를 찾는 작업.

### 🔍 동작

각 layer L에 대해:

1. logical embedding(L)
2. pragmatic embedding(L)
3. `1 – cosine(logical, pragmatic)` 계산
4. 여러 sample 평균
5. 가장 큰 값을 주는 layer = best layer

즉, **두 의미의 차이를 무조건 가장 잘 드러내는 레이어**를 자동 탐색하는 과정.

### 🎯 왜 필요?

* steering vector는 모델 내부의 “semantic direction”을 건드리는 작업임
* 의미 차이가 가장 선명한 레이어에서 작업해야 steering 효과가 최대

---

# **4. Steering Vector 생성 (Mean Difference Vector)**

### 📌 역할

logical 문장 embedding들의 평균과
pragmatic 문장 embedding들의 평균의 차이를 계산하여

→ **모델이 실제로 표현하는 뜻의 차이가 들어있는 방향 벡터(direction)** 를 만드는 단계.

### 🔍 과정

* 모든 logical 문장 embedding 평균 → L_mean
* 모든 pragmatic 문장 embedding 평균 → P_mean
* steering vector = (P_mean – L_mean)
* 방향만 중요하므로 normalize

### 🎯 의미

이 벡터가 바로 **anchor를 pragmatic 의미 쪽으로 이동시키는 힘**이 됨.

---

# **5. Alpha 설정(강도 조절)**

### 📌 역할

anchor embedding을 얼마나 강하게 pragmatic 방향으로 이동시킬지 조절.

### 🔍 방식

* 하나의 고정 α 사용 (예: 3.0)
* or grade(A–E)에 따라 다른 α 사용

### 공식

```
alpha = ALPHA_MIN + (ALPHA_MAX - ALPHA_MIN) * grade_numeric
```

### 🎯 의미

steering 강도를 점진적으로 변화시키며 의미적 이동이 linear하게 반영되는지 실험 가능.

---

# **6. evaluate_with_steering() – 핵심 평가 루프**

### 📌 역할

전체 데이터에 대해:

1. baseline internal similarity 계산
2. steering 적용 후 similarity 계산
3. preference (pragmatic이 더 가까운지 여부) 계산
4. 결과를 모두 CSV로 저장

### 🔍 세부 작업

각 row마다:

#### 🔸 Baseline

* anchor → logical cosine
* anchor → pragmatic cosine
* pragmatic 쪽이 더 가까우면 1, 아니면 0

#### 🔸 Steering

* steered_anchor = anchor_emb + α * v
* normalize
* steered_anchor vs logical
* steered_anchor vs pragmatic
* steered preference 계산

#### 🔸 저장

원본 row + baseline 결과 + steered 결과 → CSV로 기록.

### 🎯 목적

steering이 실제로 semantic preference를 바꾸는지 계량적으로 분석하기 위한 준비 단계.

---

# **7. 실행 파이프라인**

### 📌 역할

전체 실험을 통합적으로 수행.

### 단계 요약

1. 데이터 로드
2. BEST LAYER 자동 탐색
3. steering 벡터 생성
4. fixed-alpha steering 결과 생성
5. grade-alpha steering 결과 생성

### 🎯 목적

단 한 번의 실행으로 전체 실험 재현 가능.

---

# **8. 시각화(Optional)**

### 📌 역할

* baseline similarity scatter/kde plot
* steered similarity scatter/kde plot

이를 통해 steering이 어떻게 embedding 공간에서 의미의 구조를 바꿨는지 시각적으로 분석.

### 🎯 의미

논문 Figure / 발표에서 사용 가능.

---

# 📌 최종 요약 (한 문장씩)

| 번호 | 단계 이름                | 한 줄 설명                                     |
| -- | -------------------- | ------------------------------------------ |
| 0  | Imports & Model Load | 모델과 라이브러리 로드                               |
| 1  | Embedding Extraction | 문장을 특정 레이어 embedding으로 변환                  |
| 2  | Cosine Similarity    | 두 embedding의 의미적 유사도 계산                    |
| 3  | Layer Detection      | 의미 차이가 가장 잘 드러나는 레이어 탐색                    |
| 4  | Steering Vector      | pragmatic–logical 평균 차이로 방향 벡터 생성          |
| 5  | Alpha 설정             | steering 강도 조절                             |
| 6  | Evaluation Loop      | baseline + steering similarity 계산 및 CSV 저장 |
| 7  | Pipeline 실행          | 전체 실험 자동 수행                                |
| 8  | Visualization        | steering 효과를 시각적으로 확인                      |

---

# 😊 이제 예은이가 원하는 실험 구조가 훨씬 깔끔해졌어!

원하면:

* 전체 pipeline 설명을 논문 Methods에 맞게 학술적 문체로 다시 작성
* Figure caption 스타일 작성
* Steering 효과를 수치적으로 요약하는 표 자동 생성

이런 것도 도와줄게!

"""

